language: node_js
node_js:
- 7
- 8
install:
- npm install -g gulp
- npm install
script:
- npm run lint
- if [[ "$TRAVIS_PULL_REQUEST_BRANCH" =~ ^release\/.*$ ]]; then 
    git lfs pull; 
    npm run test:minified; 
  else 
    npm run build;
  fi
- npm run demo:build


